config/routes.rb
Rails.application.routes.draw do
  get 'messages/new'

  get 'messages/create'

  root to: 'visitors#index'
  devise_for :users
  resources :users
  
  #get '/jobs', to: 'jobs#index'
  #get '/jobs/new', to: 'jobs#new', as: 'new_job'
  #post '/jobs', to: 'jobs#create'
  #get '/jobs/:id/edit', to: 'jobs#edit', as: 'edit_job'
  #patch '/jobs/:id', to: 'jobs#update'
  #get '/jobs/:id', to: 'jobs#show', as: 'job'
  #delete '/jobs/:id', to: 'jobs#destroy'
  
  resources :jobs do
   resources :comments
  end
 
  match '/contacts',     to: 'contacts#new',             via: 'get'
  resources "contacts", only: [:new, :create]
  
  
  resources :messages, only: [:new, :create]
  
 
  
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :job
  belongs_to :user

  validates :body, presence: true
  
  scope :sorted, lambda { order('created_at DESC') }

end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Submission from Fix My House Test App",
      :to => "shawn@striventa.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/job.rb
class Job < ActiveRecord::Base
  #extend ::Geocoder::Model::ActiveRecord
  belongs_to :user 
  has_many :comments

  validates :user_id, presence: true
  validates :job_title, presence: true
  validates :job_address, presence: true
  validates :job_contact_name, presence: true
  validates :job_contact_phone, presence: true
  validates :job_contact_email, presence: true
  #validates :job_request_date, presence: true
  validates :job_description, presence: true
  
 geocoded_by :job_address
 after_validation :geocode

  scope :sorted, lambda { order('created_at DESC') }
  
  mount_uploader :picture, PictureUploader
  validate :picture_size
  
  private
  
  def picture_size
    if picture.size > 5.megabytes
      errors.add(:picture, "Should be less than 5MB")
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:user, :contractor, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end
  has_many :jobs
  has_many :comments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @job = Job.find(params[:job_id])
    @comment = @job.comments.create(params[:comment].permit(:commenter, :body))
    
    redirect_to job_path(@job)
  end
    
    
    
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:notice] = 'Thank you for your message. We will contact you soon!'
    else
      flash.now[:error] = 'Cannot send message.'
      render :new
    end
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

    def index
       # @jobs = Job.all
       @jobs = Job.where(user_id: current_user.id)
    end

    def show
       @job = Job.find(params[:id]) 
       #@comments = @job.comments
       #@comments = Comment.where(job_id: @job.id)
       #@comment = @job.comments.build
       @hash = Gmaps4rails.build_markers(@job) do |job, marker|
            marker.lat job.latitude
            marker.lng job.longitude
end
    end
    
    def new
        @job = Job.new
    end
    
    def create
        @job = Job.new(job_params)
        # @job.user = User.find(2)
        @job.user_id = current_user.id
        
        if @job.save
            flash[:success] = "Your Job was created successfully!"
            redirect_to jobs_path
            
        else
            render :new
        end
    
    end
    
    def edit
        @job = Job.find(params[:id])
    end
    
    def update 
        @job = Job.find(params[:id])
        if @job.update(job_params)
            flash[:success] = "Your Job was udpated successfully!"   
            redirect_to jobs_path(@job)
        else
        render :edit
        end
    end
    
    private
    
        def job_params
           params.require(:job).permit(:job_title, :job_address, :job_description, :job_contact_name, :job_contact_phone, :job_contact_email, :job_request_date, :picture)
        end
    
    
    
    
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def new
  end

  def create
    require 'textmagic'

    @phone_number = message_params[:phone_number]
    @message = message_params[:message]

    @gateway = TextMagic::API.new('shawnmorgan', 'XnytuJu9uU')
    @gateway.send message_params[:message], message_params[:phone_number]
  end

private
  def message_params
    params.require(:message).permit(:phone_number, :message)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_only, :except => :show

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless current_user.admin?
      unless @user == current_user
        redirect_to :back, :alert => "Access denied."
      end
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private

  def admin_only
    unless current_user.admin?
      redirect_to :back, :alert => "Access denied."
    end
  end

  def secure_params
    params.require(:user).permit(:role)
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController

    def show
       @job = Job.find(params[:id])  
       @comment = Comment.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/comments/_comment.html.erb
<div class="row">
    <div class="col-md-8 well">
    
    
    <div class="comment_content">
        <p class="comment_name"><strong><%= comment.commenter %></strong></p>
        <p class="comment_body"><%= comment.body %></p>
        <p class="comment_time"><%= time_ago_in_words(comment.created_at) %> Ago</p>
    </div>
</div>
</div>

app/views/comments/_form.html.erb
<div class="row">
    <div class="col-md-8 well  new-job">
        <h3>Add Comments</h3>
    <%= form_for([@job, @job.comments.build]) do |f| %>
    <p><%= f.label :commenter %><br/>
    <%= f.text_field :commenter %></p>
    
    <br>
    <p><%= f.label :body %><br />
    <%= f.text_area :body %></p>
    <br>
    <%= f.submit class: "btn btn-success" %>
    <% end %>
    </div>
</div>

app/views/contacts/create.html.erb
<div>
  <% flash.each do |key, value| %>
    <div>
      <a href="#" data-dismiss="alert">×</a>
        <%= value %>
    </div>
  <% end %>
</div>

app/views/contacts/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <h3>We Are Here For You...Really</h3>
      <%= simple_form_for @contact, :html => {:class => 'form-horizontal' } do |f| %>
      <%= f.input :name, :required => true %>
      <%= f.input :email, :required => true %>
      <%= f.input :message, :as => :text, :required => true %>
      <div class= "hidden">
        <%= f.input :nickname, :hint => 'Leave this field blank!' %>
      </div>
    <div>
      </br>
      <%= f.button :submit, 'Send message', :class=> "btn btn-primary" %>
  </div>
  <% end %>
</div>

app/views/jobs/edit.html.erb
<h1>Edit Job</h1>
<hr/>


<% if @job.errors.any? %>
    <div class="row">
        <div class="alert alert-danger col-md-8 col-md-offset-2">
            <h5>Please correct the following errors</h5>
            <ul>
                <% @job.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    </div>
<% end %>


<div class="row">
    <div class="col-md-6 well col-md-offset-2 new-job">
        <%= tinymce_assets %>
             <%= form_for(@job, html: { multipart: true }) do |f| %>
            <%= f.label :job_title %>
            <%= f.text_field :job_title %>
        
            <%= f.label :job_address %>
            <%= f.text_field :job_address %>
            
            <%= f.label :job_contact_name %>
            <%= f.text_field :job_contact_name %>
            
            <%= f.label :job_contact_phone %>
            <%= f.text_field:job_contact_phone%>
            
            <%= f.label :job_contact_email %>
            <%= f.text_field :job_contact_email %>
            
            <%= f.label :job_request_date %>
            <%= date_field :job_request_date, :class => 'datepicker' %>
            
            <%= f.label :job_description %>
            <%= f.text_area :job_description, rows: 10, class: "tinymce" %>
            
            <span class="picture">
                <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png,image/jpg' %>
            </span>
            
            
            <%= f.submit 'Edit Job', class: "btn btn-success" %>
        
        <% end %>
    </div>
</div>

<script type="text/javascript">
    $('#job_picture').bind('change', function() {
         size_in_megabytes = this.files[0].size/1024/1024;
         if (size_in_megabytes > 5) {
             alert("Maximum file size is 5MB. Please choose a smaller file.");
         }
        
        
    });
    
</script>
<%= tinymce %>

app/views/jobs/index.html.erb
<div class="container all-jobs">
    <h1 class="text-center">All Jobs</h1>
    <hr>
    <div class="row">
        <div class="col-md-2">
            <section class="user_menu center">
                <ul>
                   <li> <%= link_to 'Create New Job', new_job_path, class: "btn btn-success" %></li>
                   <li> <%= link_to 'Contact Support', new_contact_path, class: "btn btn-warning" %></li>
                   <li><%= link_to "Text Contractor", new_message_path, class: "btn btn-info" %></li>
                </ul>
                
            </section>
        </div>
        <div class="col-lg-10">
            <% @jobs.each do |job| %>
                <ul>
                    <li class="well">  
                        <div class="col-md-8">
                            <h4 class="job-title"><%= link_to job.job_title, job_path(job) %></h4>
                            <h4 class="job-address"><%= job.job_address %></h4>
                            <p>
                                <span class="quiet"><small><%= time_ago_in_words(job.created_at) %></small></span>
                            </p>
                            <span><%= job.job_state %> Job: <strong>Pending Review</strong></span> 
                        </div>
                        <div class="col-md-4">
                            <% if job.picture? %>
                            <%= image_tag(job.picture.url, size: "250x150", class: "img-responsive") if job.picture? %>
                            <% end %>
                        </div>
                    </li> 
                    <hr>
                </ul>
            <% end %>
        </div>
        
    </div>
</div>

app/views/jobs/misc.html.erb
<% if @comments %>
<% @comments.each do |comment| %>
  <div>
    <strong><%= comment.user.name %></strong>
    <br />
    <p><%= comment.body %></p>
    
  </div>
<% end %>

<% end %>




<div class="field">
    <%= form_for @comment do |f| %>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
    <%= f.submit %>
    <% end %>
  </div>
  
  
  <p class="comment_name"><strong><%= comment.user.id %></strong></p>

app/views/jobs/new.html.erb
<h1>Create a new Job</h1>
<hr/>


<% if @job.errors.any? %>
    <div class="row">
        <div class="alert alert-danger col-md-8 col-md-offset-2">
            <h5>Please correct the following errors</h5>
            <ul>
                <% @job.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    </div>
<% end %>


<div class="row">
    <div class="col-md-6 well col-md-offset-2 new-job">
        <%= tinymce_assets %>
        <%= form_for(@job, html: { multipart: true }) do |f| %>
            <%= f.label :job_title %>
            <%= f.text_field :job_title %>
        
            <%= f.label :job_address %>
            <%= f.text_field :job_address %>
            
            <%= f.label :job_contact_name %>
            <%= f.text_field :job_contact_name %>
            
            <%= f.label :job_contact_phone %>
            <%= f.text_field :job_contact_phone%>
            
            <%= f.label :job_contact_email %>
            <%= f.text_field :job_contact_email %>
            
            <%= f.label :job_request_date %>
            <%= f.date_field :job_request_date, "data-provide" => 'datepicker' %>
            
            <%= f.label :job_description %>
            <%= f.text_area :job_description, rows: 10, class: "tinymce" %>
            
            <span class="picture">
                <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
            </span>
            
            <%= f.submit 'Create Job', class: "btn btn-success" %>
        
        <% end %>
    </div>
</div>

<script type="text/javascript">
    $('#job_picture').bind('change', function() {
         size_in_megabytes = this.files[0].size/1024/1024;
         if (size_in_megabytes > 5) {
             alert("Maximum file size is 5MB. Please choose a smaller file.");
         }
        
        
    });
    
</script>
<%= tinymce %>

app/views/jobs/show.html.erb
<div class="container"

<p>
    <h1><%= @job.job_title %></h1>
</p>
<div class="row">
    <div class="col-md-8 well">
        <%= link_to "Edit Job", edit_job_path(@job), class: "btn btn-success pull-right" %>
        <h3><address> <%= @job.job_address %></address></h3>
        <div style='width: 80%;'>
          <div id="map" style='width: 650px; height: 300px;'>
              <script>
                    markers = handler.addMarkers(<%=raw @hash.to_json %>);
              </script>
              
          </div>
          <script type="text/javascript">
                handler = Gmaps.build('Google');
                handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
                  
                     markers = handler.addMarkers(<%=raw @hash.to_json %>);
                  handler.bounds.extendWith(markers);
                  handler.fitMapToBounds();
                  handler.map.serviceObject.setZoom(16);
                });
          </script>
        </div>
        <p><%= @job.latitude %> , <%= @job.longitude %></p>
        <h4>Contact Details</h4>
        <hr/>
        <p>Contact Name: <strong><%= @job.job_contact_name %></strong></p>
        <p>Contact Phone: <strong><%= @job.job_contact_phone %></strong></p>
        <p>Contact Email: <strong><%= @job.job_contact_email %></strong></p>
        <hr/>
        <p>Job Request Date: <strong><%= simple_format(@job.job_request_date) %></strong></p>
        <hr/>
        <h4>Job Description</h4>
        <p><%= simple_format(@job.job_description) %></p>
        <span class="pull-right"><%= @job.job_state %> Job: <strong>Pending Review</strong></span>        
    </div>
        <div class="col-md-4 pull-right center">
        <h4>Job Images</h4>
        <% if @job.picture? %>
        <%= image_tag(@job.picture.url, size: "250x150", class: "img-responsive") if @job.picture? %>
        <% else %>
        <p class="text-left">There are no pictures. <%= link_to "Edit Job", edit_job_path(@job) %> to add pictures.</p>
        <% end %>
    </div>
    
</div>



<h3>Comments</h3>
<h5><%= @job.comments.count class: "pull-right" %> Comments</h5>
<%= render @job.comments %>


<%= render "comments/form" %>


<div class="row">
<div class="col-md-3"><%= link_to 'Return to All Jobs', jobs_path, class: "btn btn-warning btn-small" %></div>
<div class="col-md-3"><%= link_to 'Contact Support', new_contact_path, class: "btn btn-danger" %></div>
<div class="col-md-3"><%= link_to "Text Contractor", new_message_path, class: "btn btn-info" %></div>
</div>

</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Profile', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <% if current_user.try(:admin?) %>
    <li><%= link_to 'Users', users_path %></li>
  <% end %>
  <% if current_user.try(:contractor?) %>
    <li><%= link_to 'Assigned Jobs', assigned_path %></li>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
        <%= render 'layouts/nav_links_for_auth' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'My Jobs', jobs_path %></li>
<li><%= link_to 'About', page_path('about') %></li>
<li><%= link_to 'Contact', contacts_path %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Fix My House" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Fix My House" %>">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
    <script src="//maps.google.com/maps/api/js?v=3.18&sensor=false&client=&key=&libraries=geometry&language=&hl=&region="></script> 
    <script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js"></script>
    <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/infobox/1.1.9/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->
    
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/messages/create.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <h2 class="text-center">Message Sent!</h2>
<p class="text-center">
<%= "The message to #{@phone_number} containing the text '#{@message}' has been sent successfully!" %>
</p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3"><%= link_to 'Return to All Jobs', jobs_path, class: "btn btn-warning btn-small" %></div>
        <div class="col-md-3"><%= link_to 'Contact Support', new_contact_path, class: "btn btn-danger" %></div>
        <div class="col-md-3"><%= link_to "Text Contractor", new_message_path, class: "btn btn-info" %></div>
    </div>
</div>

app/views/messages/new.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <h2 class="text-center">Text Your Contractor</h2>
            <hr/>
            <%= form_for :message, url: messages_path do |f| %>
            <p><%= f.label :phone_number %><br/>
            <%= f.text_field :phone_number %></p>
            <p><%= f.label :message %><br/>
            <%= f.text_field :message %></p>
            <%= f.submit "Send Message", class: "btn btn-info" %>
            <% end %>
        </div>
    </div>
</div>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
This application is the test for Fix My House
</p>

app/views/users/_user.html.erb
<td>
  <%= link_to user.email, user %>
</td>
<td>
  <%= form_for(user) do |f| %>
    <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
    <%= f.submit 'Change Role', :class => 'button-xs' %>
  <% end %>
</td>
<td>
  <%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs') unless user == current_user %>
</td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>

app/views/visitors/index.html.erb
<% if user_signed_in? %>
<div class="container">
<div class="row">
    <div class="col-md-12">
        <h1 class="text-center">Welcome Back </h1>
    </div>
<hr>
<br/>
</div>
<div class="row">
    <div class="col-md-4">
        <h3>Latest Comments</h3>
        <% @comments = Comment.where(user_id: current_user.id) %>
        <% @comments.each do |comment| %>
        <div class="well">
            <%= comment.commenter %><br/>
            <%= comment.body %><br/>
            <%= time_ago_in_words(comment.created_at) %> Ago
        </div>
        <% end %>
    </div>
    <div class="col-md-4">
        <h3>Latest Jobs</h3>
        <% @jobs = Job.where(user_id: current_user.id) %>
        <% @jobs.each do |job| %>
        <p><%= link_to job.job_title, job_path(job) %></p>
        <% end %> 
        
    </div>
    <div class="col-md-4">
        <h3>Notifications</h3>
        <p>There are no notifications</p>
    </div>    


</div>
<hr>
<br/>
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="col-md-3"><%= link_to 'See All Jobs', jobs_path, class: "btn btn-warning btn-small" %></div>
        <div class="col-md-3"><%= link_to 'Create New Job', new_job_path, class: "btn btn-success" %></div>
        <div class="col-md-3"><%= link_to 'Contact Support', new_contact_path, class: "btn btn-danger" %></div>
        <div class="col-md-3"><%= link_to "Text Contractor", new_message_path, class: "btn btn-info" %></div>
    </div>
</div>
</div>
<% else %>
<div class="container">
<br>
<br>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <h1 class="text-center">Welcome to the<br> Fix My House<br> Test App</h1>
        <p class="text-center">Please excuse the mess. We are working hard to get everything perfect for you.</p>
        <br>
        <p class="text-center">
        <%= link_to 'Sign up', new_user_registration_path, class: "btn btn-warning btn-large text-center" %>
        </p>
        <p class="text-center">
        <%= link_to 'Sign in', new_user_session_path, class: "btn btn-success btn-large text-center" %>
        </p>
    </div>


<% end %>

</div>
    
    
    
</div>